### ISSUE TITLE
Great work, slight issue

### ISSUE THREAD

**Issue by swynter-ladbrokes** [hellvinz/goredis#1]
Greetings

Works great, but found that it can't parse QUIT (it seems) - I added a print to the top of the parse function

`````` *3
$4
HGET
$34
work:day=2015-08-05:event=11073883
$13
comp:47833254

QUIT

RedisParser_error
*3
$8
REPLCONF
$3
ACK
$11
76978846912```
``````

**Comment by hellvinz** [comment]
hey!
thanks for the feedback, I haven't been able to reproduce unfortunately. From my understanding of QUIT and the redis-cli souce https://github.com/antirez/redis/blob/2.8/src/redis-cli.c#L957, I don't think that QUIT will reach the redis-server, it just close the redis-cli process

**Comment by freman** [comment]
That's what I thought as well, but every time I type "quit" into a client RedisParser_error happens. I don't expect it to be an issue in our production tho, I just thought it odd and worth mentioning.

**Comment by swynter-ladbrokes** [comment]
Actually, Turns out it happens a butload in our production env :(

{code}
RedisParser_error
RedisParser_error
RedisParser_error
RedisParser_error
RedisParser_first_final
{code}

**Comment by swynter-ladbrokes** [comment]
Here's a specific RedisParser_error

```
*4
$5
SETEX
$29
previous:cache:thing:11841428
$2
30
$0


```

I read that as 4 item array [string 5{SETEX}, string 29{previous:cache:thing:11841428}, string 2{30}string 0{}]

Last entry being null "$0\r\n\r\n"

Is that what it's having issue with?

Edit: this is the structure it has at the time of failing

```
&main.RedisCommand{argnum:4, argsize:0, cur_arg:3, cur_arg_char:0, Args:[][]uint8{[]uint8{0x53, 0x45, 0x54, 0x45, 0x58}, []uint8{0x70, 0x72, 0x65, 0x76, 0x69, 0x6f, 0x75, 0x73, 0x3a, 0x63, 0x61, 0x63, 0x68, 0x65, 0x3a, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x3a, 0x31, 0x31, 0x38, 0x34, 0x31, 0x34, 0x32, 0x38}, []uint8{0x33, 0x30}, []uint8{}}, args_sizes:[]int{5, 29, 2, 0}, Ipaddr:[]uint8{}}
```

Edit:

```
redis_parser_exec("*4\r\n$5\r\nSETEX\r\n$29\r\nprevious:cache:thing:11841428\r\n$2\r\n30\r\n$0\r\n\r\n")
```

Fails every time whereas

```
redis_parser_exec("*4\r\n$5\r\nSETEX\r\n$29\r\nprevious:cache:thing:11841428\r\n$2\r\n30\r\n$2\r\nhi\r\n")
```

Works fine

**Comment by hellvinz** [comment]
this should be ok now https://github.com/hellvinz/goredis/commit/f9ef398c02f673921a26283078917129f196a848
