### ISSUE TITLE
Can't build UI, Bower unable to satisfy bootstrap-sass#~2.3.1

### ISSUE THREAD

**Issue by swynter-ladbrokes** [hellvinz/goredis#2]
bower bootstrap-sass#~2.3.1                                   ENORESTARGET No tag found that was able to satisfy ~2.3.1

Additional error details:
Available versions: 3.3.5, 3.3.4, 3.3.3, 3.3.2+1, 3.3.2, 3.3.1, 3.3.0, 3.2.0+2, 3.2.0+1, 3.2.0, 3.1.1+2, 3.1.1+1, 3.1.1, 3.1.0, 3.1.0+2, 3.0.3-0, 2.0.3, 2.0.2, 2.0.1, 2.0.0, 1.4.4, 1.4.3, 1.4.2, 1.4.1, 1.4.0, 1.3.2, 1.3.1, 1.3.0, 1.2.1, 1.2.0

Makes me sad :(

**Comment by hellvinz** [comment]
this should be fixed by https://github.com/hellvinz/goredis/commit/17ffba279819e458217fdd5aae8a4aa5acd616bc
